Add missing build dependencies on boost (#725)
Without this, compilation can fail with errors like:

    /build/SMACC2-release-release-jazzy-forward_global_planner-3.1.0-2/src/forward_global_planner/forward_global_planner.cpp:28:10:
    fatal error: boost/assign.hpp: No such file or directory
       28 | #include <boost/assign.hpp>
          |          ^~~~~~~~~~~~~~~~~~ robosoft-ai/SMACC2@da9be86f60ee5010a3f1520a809d7e0db8043f8c